### ISSUE TITLE
Epub format

### ISSUE THREAD

**Issue by Ahmed-Ali** [OpenIntroStat/openintro-statistics#42]
Not sure how hard this might be, but if it is not too much work, epub is pretty portable format. Main advantages include responsive sizing (nice when one wants to zoom in for bigger text on tablets), and flexible coloring, which makes it nice for dark mode. PDF is subtle with these things.

Thank you for the amazing efforts :)

**Comment by DavidDiez** [comment]
We've looked into this quite closely and determined it would be too much work to be worth it, so we don't plan to make this update.

For reference, one other book (openintro.org/book/ims) has pursued this option (it turned out to be even more work than expected), so there is one OpenIntro textbook that can be read on the web, but it is likely not something that will be pursue with other textbooks.

**Comment by Ahmed-Ali** [comment]
Thanks David for the prompt response. I understand it can get quite complex. My previous experience trying to format things into epub ended up building a project to automate it (for totally different context and was very scoped, yet was bit of work). Appreciate your quick response though.

Do you happen to have a link to the online readable one? I mean is it web based? if so, at least that can be bit more responsive than the PDF. Thanks!

**Comment by nicholasjhorton** [comment]
I found it at https://openintro-ims.netlify.app

**Comment by Ahmed-Ali** [comment]
I managed to use my local software to convert the web version into a readable epub (it is around 50MB after zipping so unable to attach here). If anyone interested in it even for curiosity reason, let me know and I can forward to you
![Screenshot 2021-02-12 at 16 37 25](https://user-images.githubusercontent.com/5157350/107795502-a18b3c00-6d50-11eb-87cb-d99c1517e5aa.png)

**Comment by mine-cetinkaya-rundel** [comment]
@Ahmed-Ali I'd be interested in hearing about whether epub version offers something different than the web version of IMS offers. Since we won't be offering an epub version of OpenIntro Statistics, we can keep that conversation at https://github.com/openintrostat/ims. Feel free to open an issue there!

And to be clear, we haven't necessarily abandoned that option for IMS, but it wasn't a priority on my radar (we're currently focusing on HTML and PDF versions of the book).
