### ISSUE TITLE
Ch 7: Typo in Hypothesis Testing Instructions

### ISSUE THREAD

**Issue by waldo1979** [OpenIntroStat/openintro-statistics#48]
The is a typo on page 258, Chapter 7, Section 7.15, towards the bottom of the page.

In the table labeled "Hypothesis Testing for a single mean", the "Check" step read as:
"Verify conditions to ensure x-bar is nearly normal"

The x-bar should be the set of x values ( {x} ), not the mean of x.

**Comment by DavidDiez** [comment]
The description is accurate, because we need to consider the influence of the Central Limit Theorem. This is discussed in more detail in Section 7.1.2 (p251). For example, if the sample size is ≥30, then some skew in the distribution of individual observations is okay, provided that skew is not extreme.
